# Utiliser l'image officielle de MongoDB
FROM mongo:6.0.5-focal

# Définir le répertoire de travail dans le conteneur
WORKDIR /data/db

# Exposer le port par défaut de MongoDB
EXPOSE 27017

# Commande pour démarrer MongoDB
CMD ["mongod"]