name: CI stats microservice dev and feature

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - develop
      - feature/*

jobs:

  lint:
    name: Code Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install flake8
        run: pip install flake8

      - name: Run Flake8 Linter
        run: flake8 --max-line-length=300 --exclude=venv

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: pytest ./tests --junitxml=report.xml